version: 2
models:
  - name: nba_player_game_logs
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "loaded_at_dttm"
          # optional - use tags to run elementary tests on a dedicated run
          tags: ["elementary"]
          config:
            # optional - change severity
            severity: warn
            