version: 2
models:
  - name: nba_player_game_logs
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: "loaded_at_dttm"
          time_bucket: 
            period: day
            count: 1
          detection_period: 
            period: day
            count: 14
          training_period: 
            period: day
            count: 60
          anomaly_sensitivity: 3
          detection_delay: 
            period: day 
            count: 1
          config:
            severity: warn
