version: 2

models:
  - name: nba_player_game_logs
    columns:
      - name: player_id
        tests:
          - not_null
      - name: player_name
        tests:
          - not_null
      - name: nickname
        tests:
          - not_null
      - name: team_id
        tests:
          - not_null
      - name: team_abbreviation
        tests:
          - not_null
      - name: team_name
        tests:
          - not_null
      - name: game_id
        tests:
          - not_null
      - name: game_date
        tests:
          - not_null
      - name: matchup
        tests:
          - not_null
      - name: wl
      - name: mins_played
      - name: field_goals_made
      - name: field_goals_attempted
      - name: field_goal_pct
      - name: three_point_made
      - name: three_point_attempted
      - name: three_point_pct
      - name: free_throws_made
      - name: free_throws_attempted
      - name: free_throw_pct
      - name: offensive_rebounds
      - name: defensive_rebounds
      - name: total_rebounds
      - name: assists
      - name: turnovers
      - name: steals
      - name: blocks
      - name: personal_fouls
      - name: points
      - name: plus_minus
      - name: season
      - name: game_type
        tests:
          - not_null
          - accepted_values:
              values: ["Regular Season", "Playoffs"]
      - name: loaded_at_dttm
        tests:
          - not_null